apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pai-production-green

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/escape-velocity-ventures/pai-state-service
    newTag: unified-search
