apiVersion: v1
kind: Service
metadata:
  name: pai-state-service
  namespace: pai-staging
  labels:
    app: pai-state-service
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: pai-state-service
  ports:
  - name: http
    port: 80
    targetPort: 3000
