apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: pai-blog
  labels:
    app.kubernetes.io/name: ghost
spec:
  type: ClusterIP
  ports:
    - port: 2368
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ghost
