apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: pai-blog
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  # Change to longhorn-2-replicas when Longhorn is deployed
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
